folder_data:
  folder_path: /home/tung/Downloads/DE_K3_M2/project/data/pump

datalake:
  endpoint: localhost:9000
  bucket_name: nyc-taxi-data
  folder_name: pump
  access_key: minio_access_key
  secret_key: minio_secret_key